const BAKED_DATA = {
    "matches": [
        {
            "id": 1,
            "teamA": "Juanma Leon / Raquel Fdez",
            "teamB": "David Asen / Anais",
            "scoreA": 2,
            "scoreB": 3,
            "court": "Pista 2",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 2,
            "teamA": "Paula / Jose Luis Berga",
            "teamB": "Alex C / Pili Jor",
            "scoreA": 2,
            "scoreB": 6,
            "court": "Pista 3",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 3,
            "teamA": "Juanma Leon / Raquel Fdez",
            "teamB": "Paula / Jose Luis Berga",
            "scoreA": 2,
            "scoreB": 1,
            "court": "Pista 2",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 4,
            "teamA": "David Asen / Anais",
            "teamB": "Alex C / Pili Jor",
            "scoreA": 1,
            "scoreB": 5,
            "court": "Pista 3",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 5,
            "teamA": "Juanma Leon / Raquel Fdez",
            "teamB": "Alex C / Pili Jor",
            "scoreA": 3,
            "scoreB": 1,
            "court": "Pista 2",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 6,
            "teamA": "David Asen / Anais",
            "teamB": "Paula / Jose Luis Berga",
            "scoreA": 3,
            "scoreB": 4,
            "court": "Pista 3",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 7,
            "teamA": "Toni M / Sonia",
            "teamB": "Kevin / Lorena",
            "scoreA": 5,
            "scoreB": 1,
            "court": "Pista 5",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 8,
            "teamA": "Joaquim Salvat / Monica",
            "teamB": "Javier Frauca / Natalia",
            "scoreA": 3,
            "scoreB": 6,
            "court": "Pista 6",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 9,
            "teamA": "Toni M / Sonia",
            "teamB": "Joaquim Salvat / Monica",
            "scoreA": 1,
            "scoreB": 4,
            "court": "Pista 5",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 10,
            "teamA": "Kevin / Lorena",
            "teamB": "Javier Frauca / Natalia",
            "scoreA": 6,
            "scoreB": 4,
            "court": "Pista 6",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 11,
            "teamA": "Toni M / Sonia",
            "teamB": "Javier Frauca / Natalia",
            "scoreA": 3,
            "scoreB": 5,
            "court": "Pista 5",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 12,
            "teamA": "Kevin / Lorena",
            "teamB": "Joaquim Salvat / Monica",
            "scoreA": 3,
            "scoreB": 6,
            "court": "Pista 6",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 13,
            "teamA": "Sonia / Miguel",
            "teamB": "Carlota / Jordi Seuba",
            "scoreA": 2,
            "scoreB": 6,
            "court": "Pista 7",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 14,
            "teamA": "Enrique F / Annabel",
            "teamB": "Cristina / Carlos",
            "scoreA": 6,
            "scoreB": 5,
            "court": "Pista 8",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 15,
            "teamA": "Sonia / Miguel",
            "teamB": "Enrique F / Annabel",
            "scoreA": 4,
            "scoreB": 3,
            "court": "Pista 7",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 16,
            "teamA": "Carlota / Jordi Seuba",
            "teamB": "Cristina / Carlos",
            "scoreA": 1,
            "scoreB": 2,
            "court": "Pista 8",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 17,
            "teamA": "Sonia / Miguel",
            "teamB": "Cristina / Carlos",
            "scoreA": 1,
            "scoreB": 2,
            "court": "Pista 7",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 18,
            "teamA": "Carlota / Jordi Seuba",
            "teamB": "Enrique F / Annabel",
            "scoreA": 4,
            "scoreB": 1,
            "court": "Pista 8",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 19,
            "teamA": "Marta Murigaren / Jorge Rueda",
            "teamB": "Coral / Ismael",
            "scoreA": 4,
            "scoreB": 2,
            "court": "Pista 9",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "D",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 20,
            "teamA": "Luis Pino / Raquel Perez",
            "teamB": "Fernando / Sobrina Fernando",
            "scoreA": 4,
            "scoreB": 2,
            "court": "Pista 10",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "D",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 21,
            "teamA": "Marta Murigaren / Jorge Rueda",
            "teamB": "Luis Pino / Raquel Perez",
            "scoreA": 1,
            "scoreB": 5,
            "court": "Pista 9",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "D",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 22,
            "teamA": "Coral / Ismael",
            "teamB": "Fernando / Sobrina Fernando",
            "scoreA": 4,
            "scoreB": 2,
            "court": "Pista 10",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "D",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 23,
            "teamA": "Marta Murigaren / Jorge Rueda",
            "teamB": "Fernando / Sobrina Fernando",
            "scoreA": 6,
            "scoreB": 3,
            "court": "Pista 9",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "D",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 24,
            "teamA": "Coral / Ismael",
            "teamB": "Luis Pino / Raquel Perez",
            "scoreA": 5,
            "scoreB": 4,
            "court": "Pista 10",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "D",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 1024,
            "matchName": "Cuartos 1",
            "teamA": "Alex C / Pili Jor",
            "teamB": "Marta Murigaren / Jorge Rueda",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Mixta",
            "time": "16:30",
            "court": "Pista ?"
        },
        {
            "id": 1025,
            "matchName": "Cuartos 2",
            "teamA": "Joaquim Salvat / Monica",
            "teamB": "Cristina / Carlos",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Mixta",
            "time": "16:30",
            "court": "Pista ?"
        },
        {
            "id": 1026,
            "matchName": "Cuartos 3",
            "teamA": "Carlota / Jordi Seuba",
            "teamB": "Javier Frauca / Natalia",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Mixta",
            "time": "16:30",
            "court": "Pista ?"
        },
        {
            "id": 1027,
            "matchName": "Cuartos 4",
            "teamA": "Luis Pino / Raquel Perez",
            "teamB": "Juanma Leon / Raquel Fdez",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Mixta",
            "time": "16:30",
            "court": "Pista ?"
        },
        {
            "id": 2028,
            "matchName": "Semi 1",
            "teamA": "Ganador Cuartos 1",
            "teamB": "Ganador Cuartos 2",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "4ª Mixta",
            "time": "17:30",
            "court": "Pista ?"
        },
        {
            "id": 2029,
            "matchName": "Semi 2",
            "teamA": "Ganador Cuartos 3",
            "teamB": "Ganador Cuartos 4",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "4ª Mixta",
            "time": "17:30",
            "court": "Pista ?"
        },
        {
            "id": 3030,
            "matchName": "Final",
            "teamA": "Ganador Semi 1",
            "teamB": "Ganador Semi 2",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "final",
            "category": "4ª Mixta",
            "time": "18:30",
            "court": "Pista 1"
        },
        {
            "id": 32,
            "teamA": "Sergio Albert / Joan Bernard",
            "teamB": "Oscar Cosco / Javier Hita",
            "scoreA": 4,
            "scoreB": 2,
            "court": "Pista 11",
            "time": "13:30",
            "category": "4ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 33,
            "teamA": "Vlady / Bernat",
            "teamB": "Juan Manuel / Fernando",
            "scoreA": 5,
            "scoreB": 2,
            "court": "Pista 12",
            "time": "13:30",
            "category": "4ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 34,
            "teamA": "Sergio Albert / Joan Bernard",
            "teamB": "Vlady / Bernat",
            "scoreA": 5,
            "scoreB": 3,
            "court": "Pista 11",
            "time": "14:00",
            "category": "4ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 35,
            "teamA": "Oscar Cosco / Javier Hita",
            "teamB": "Juan Manuel / Fernando",
            "scoreA": 4,
            "scoreB": 6,
            "court": "Pista 12",
            "time": "14:00",
            "category": "4ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 36,
            "teamA": "Sergio Albert / Joan Bernard",
            "teamB": "Juan Manuel / Fernando",
            "scoreA": 6,
            "scoreB": 3,
            "court": "Pista 11",
            "time": "14:30",
            "category": "4ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 37,
            "teamA": "Oscar Cosco / Javier Hita",
            "teamB": "Vlady / Bernat",
            "scoreA": 2,
            "scoreB": 3,
            "court": "Pista 12",
            "time": "14:30",
            "category": "4ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 38,
            "teamA": "Adria Boza / Jugador 3MB",
            "teamB": "Cristian Gallego / Amigo Cristian",
            "scoreA": 2,
            "scoreB": 3,
            "court": "Pista 13",
            "time": "13:30",
            "category": "4ª Masculina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 39,
            "teamA": "Xavi Perea / Amigo Perea",
            "teamB": "Daniel Astasio / Pareja Daniel",
            "scoreA": 1,
            "scoreB": 3,
            "court": "Pista 14",
            "time": "13:30",
            "category": "4ª Masculina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 40,
            "teamA": "Adria Boza / Jugador 3MB",
            "teamB": "Xavi Perea / Amigo Perea",
            "scoreA": 3,
            "scoreB": 5,
            "court": "Pista 13",
            "time": "14:00",
            "category": "4ª Masculina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 41,
            "teamA": "Cristian Gallego / Amigo Cristian",
            "teamB": "Daniel Astasio / Pareja Daniel",
            "scoreA": 4,
            "scoreB": 3,
            "court": "Pista 14",
            "time": "14:00",
            "category": "4ª Masculina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 42,
            "teamA": "Adria Boza / Jugador 3MB",
            "teamB": "Daniel Astasio / Pareja Daniel",
            "scoreA": 4,
            "scoreB": 6,
            "court": "Pista 13",
            "time": "14:30",
            "category": "4ª Masculina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 43,
            "teamA": "Cristian Gallego / Amigo Cristian",
            "teamB": "Xavi Perea / Amigo Perea",
            "scoreA": 5,
            "scoreB": 4,
            "court": "Pista 14",
            "time": "14:30",
            "category": "4ª Masculina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 4043,
            "matchName": "Semi 1",
            "teamA": "Sergio Albert / Joan Bernard",
            "teamB": "Daniel Astasio / Pareja Daniel",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "4ª Masculina",
            "time": "16:30",
            "court": "Pista ?"
        },
        {
            "id": 4044,
            "matchName": "Semi 2",
            "teamA": "Cristian Gallego / Amigo Cristian",
            "teamB": "Vlady / Bernat",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "4ª Masculina",
            "time": "16:30",
            "court": "Pista ?"
        },
        {
            "id": 5045,
            "matchName": "Final",
            "teamA": "Ganador Semi 1",
            "teamB": "Ganador Semi 2",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "final",
            "category": "4ª Masculina",
            "time": "17:30",
            "court": "Pista 1"
        },
        {
            "id": 47,
            "teamA": "Cristina Matamala / Olga Ferer",
            "teamB": "Judith Esquerre / Judit Pinad",
            "scoreA": 6,
            "scoreB": 4,
            "court": "Pista 1",
            "time": "13:30",
            "category": "4ª Femenina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 48,
            "teamA": "Anna Polo / Anna Gaseni",
            "teamB": "Noe / Pareja Noe",
            "scoreA": 2,
            "scoreB": 6,
            "court": "Pista 4",
            "time": "13:30",
            "category": "4ª Femenina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 49,
            "teamA": "Cristina Matamala / Olga Ferer",
            "teamB": "Anna Polo / Anna Gaseni",
            "scoreA": 4,
            "scoreB": 3,
            "court": "Pista 1",
            "time": "14:00",
            "category": "4ª Femenina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 50,
            "teamA": "Judith Esquerre / Judit Pinad",
            "teamB": "Noe / Pareja Noe",
            "scoreA": 1,
            "scoreB": 2,
            "court": "Pista 4",
            "time": "14:00",
            "category": "4ª Femenina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 51,
            "teamA": "Cristina Matamala / Olga Ferer",
            "teamB": "Noe / Pareja Noe",
            "scoreA": 6,
            "scoreB": 5,
            "court": "Pista 1",
            "time": "14:30",
            "category": "4ª Femenina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 52,
            "teamA": "Judith Esquerre / Judit Pinad",
            "teamB": "Anna Polo / Anna Gaseni",
            "scoreA": 6,
            "scoreB": 2,
            "court": "Pista 4",
            "time": "14:30",
            "category": "4ª Femenina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 53,
            "teamA": "Sandra Riera / Yolanda",
            "teamB": "Gemma Sav / Mayte Vega",
            "scoreA": 1,
            "scoreB": 5,
            "court": "Pista 1",
            "time": "15:00",
            "category": "4ª Femenina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 54,
            "teamA": "Maria Lluisa / Pareja",
            "teamB": "Berta / Andrea",
            "scoreA": 2,
            "scoreB": 1,
            "court": "Pista 4",
            "time": "15:00",
            "category": "4ª Femenina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 55,
            "teamA": "Sandra Riera / Yolanda",
            "teamB": "Maria Lluisa / Pareja",
            "scoreA": 6,
            "scoreB": 3,
            "court": "Pista 1",
            "time": "15:30",
            "category": "4ª Femenina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 56,
            "teamA": "Gemma Sav / Mayte Vega",
            "teamB": "Berta / Andrea",
            "scoreA": 4,
            "scoreB": 2,
            "court": "Pista 4",
            "time": "15:30",
            "category": "4ª Femenina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 57,
            "teamA": "Sandra Riera / Yolanda",
            "teamB": "Berta / Andrea",
            "scoreA": 5,
            "scoreB": 6,
            "court": "Pista 1",
            "time": "16:00",
            "category": "4ª Femenina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 58,
            "teamA": "Gemma Sav / Mayte Vega",
            "teamB": "Maria Lluisa / Pareja",
            "scoreA": 2,
            "scoreB": 4,
            "court": "Pista 4",
            "time": "16:00",
            "category": "4ª Femenina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 59,
            "teamA": "Yoana Martinez / Andrea Baraja",
            "teamB": "Marta Bassons / Joana",
            "scoreA": 3,
            "scoreB": 2,
            "court": "Pista 7",
            "time": "15:00",
            "category": "4ª Femenina",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 60,
            "teamA": "Sheila Jodar / Greis Caballero",
            "teamB": "Marta Baijet / Mireia Peligros",
            "scoreA": 4,
            "scoreB": 6,
            "court": "Pista 10",
            "time": "15:00",
            "category": "4ª Femenina",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 61,
            "teamA": "Yoana Martinez / Andrea Baraja",
            "teamB": "Sheila Jodar / Greis Caballero",
            "scoreA": 3,
            "scoreB": 6,
            "court": "Pista 7",
            "time": "15:30",
            "category": "4ª Femenina",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 62,
            "teamA": "Marta Bassons / Joana",
            "teamB": "Marta Baijet / Mireia Peligros",
            "scoreA": 2,
            "scoreB": 6,
            "court": "Pista 10",
            "time": "15:30",
            "category": "4ª Femenina",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 63,
            "teamA": "Yoana Martinez / Andrea Baraja",
            "teamB": "Marta Baijet / Mireia Peligros",
            "scoreA": 5,
            "scoreB": 2,
            "court": "Pista 7",
            "time": "16:00",
            "category": "4ª Femenina",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 64,
            "teamA": "Marta Bassons / Joana",
            "teamB": "Sheila Jodar / Greis Caballero",
            "scoreA": 3,
            "scoreB": 5,
            "court": "Pista 10",
            "time": "16:00",
            "category": "4ª Femenina",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 1064,
            "matchName": "Cuartos 1",
            "teamA": "Cristina Matamala / Olga Ferer",
            "teamB": "3º Mejor (1)",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Femenina",
            "time": "16:30",
            "court": "Pista ?"
        },
        {
            "id": 1065,
            "matchName": "Cuartos 2",
            "teamA": "Maria Lluisa / Pareja",
            "teamB": "Marta Baijet / Mireia Peligros",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Femenina",
            "time": "16:30",
            "court": "Pista ?"
        },
        {
            "id": 1066,
            "matchName": "Cuartos 3",
            "teamA": "Gemma Sav / Mayte Vega",
            "teamB": "3º Mejor (2)",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Femenina",
            "time": "16:30",
            "court": "Pista ?"
        },
        {
            "id": 1067,
            "matchName": "Cuartos 4",
            "teamA": "Sheila Jodar / Greis Caballero",
            "teamB": "Noe / Pareja Noe",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Femenina",
            "time": "16:30",
            "court": "Pista ?"
        },
        {
            "id": 2068,
            "matchName": "Semi 1",
            "teamA": "Ganador Cuartos 1",
            "teamB": "Ganador Cuartos 2",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "4ª Femenina",
            "time": "17:30",
            "court": "Pista ?"
        },
        {
            "id": 2069,
            "matchName": "Semi 2",
            "teamA": "Ganador Cuartos 3",
            "teamB": "Ganador Cuartos 4",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "4ª Femenina",
            "time": "17:30",
            "court": "Pista ?"
        },
        {
            "id": 3070,
            "matchName": "Final",
            "teamA": "Ganador Semi 1",
            "teamB": "Ganador Semi 2",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "final",
            "category": "4ª Femenina",
            "time": "18:30",
            "court": "Pista 1"
        },
        {
            "id": 72,
            "teamA": "Monica / Miki Muñoz",
            "teamB": "David Navea / Ainhoa Navea",
            "scoreA": 2,
            "scoreB": 3,
            "court": "Pista 5",
            "time": "15:00",
            "category": "3ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 73,
            "teamA": "Manuel / Zizi",
            "teamB": "Maika / Josep Maria",
            "scoreA": 4,
            "scoreB": 6,
            "court": "Pista 6",
            "time": "15:00",
            "category": "3ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 74,
            "teamA": "Monica / Miki Muñoz",
            "teamB": "Manuel / Zizi",
            "scoreA": 2,
            "scoreB": 3,
            "court": "Pista 5",
            "time": "15:30",
            "category": "3ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 75,
            "teamA": "David Navea / Ainhoa Navea",
            "teamB": "Maika / Josep Maria",
            "scoreA": 2,
            "scoreB": 1,
            "court": "Pista 6",
            "time": "15:30",
            "category": "3ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 76,
            "teamA": "Monica / Miki Muñoz",
            "teamB": "Maika / Josep Maria",
            "scoreA": 1,
            "scoreB": 5,
            "court": "Pista 5",
            "time": "16:00",
            "category": "3ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 77,
            "teamA": "David Navea / Ainhoa Navea",
            "teamB": "Manuel / Zizi",
            "scoreA": 1,
            "scoreB": 5,
            "court": "Pista 6",
            "time": "16:00",
            "category": "3ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 78,
            "teamA": "Ronny / Carla",
            "teamB": "Juanjo / Mariona",
            "scoreA": 2,
            "scoreB": 3,
            "court": "Pista 8",
            "time": "15:00",
            "category": "3ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 79,
            "teamA": "Ramon / Lola",
            "teamB": "Vane / Mario",
            "scoreA": 1,
            "scoreB": 3,
            "court": "Pista 9",
            "time": "15:00",
            "category": "3ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 80,
            "teamA": "Ronny / Carla",
            "teamB": "Ramon / Lola",
            "scoreA": 1,
            "scoreB": 3,
            "court": "Pista 8",
            "time": "15:30",
            "category": "3ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 81,
            "teamA": "Juanjo / Mariona",
            "teamB": "Vane / Mario",
            "scoreA": 5,
            "scoreB": 1,
            "court": "Pista 9",
            "time": "15:30",
            "category": "3ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 82,
            "teamA": "Ronny / Carla",
            "teamB": "Vane / Mario",
            "scoreA": 3,
            "scoreB": 1,
            "court": "Pista 8",
            "time": "16:00",
            "category": "3ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 83,
            "teamA": "Juanjo / Mariona",
            "teamB": "Ramon / Lola",
            "scoreA": 3,
            "scoreB": 1,
            "court": "Pista 9",
            "time": "16:00",
            "category": "3ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 4083,
            "matchName": "Semi 1",
            "teamA": "Maika / Josep Maria",
            "teamB": "Ronny / Carla",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "3ª Mixta",
            "time": "16:30",
            "court": "Pista ?"
        },
        {
            "id": 4084,
            "matchName": "Semi 2",
            "teamA": "Juanjo / Mariona",
            "teamB": "Manuel / Zizi",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "3ª Mixta",
            "time": "16:30",
            "court": "Pista ?"
        },
        {
            "id": 5085,
            "matchName": "Final",
            "teamA": "Ganador Semi 1",
            "teamB": "Ganador Semi 2",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "final",
            "category": "3ª Mixta",
            "time": "17:30",
            "court": "Pista 1"
        },
        {
            "id": 87,
            "teamA": "Angel Millan / Albert Estrella",
            "teamB": "Gerardo / Pablo Mena",
            "scoreA": 4,
            "scoreB": 2,
            "court": "Pista 11",
            "time": "15:00",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 88,
            "teamA": "Sergio Serrano / Amigo Sergio",
            "teamB": "Eloy / Ness",
            "scoreA": 2,
            "scoreB": 6,
            "court": "Pista 12",
            "time": "15:00",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 89,
            "teamA": "Pareja 5A / Pareja 5B",
            "teamB": "Pareja 6A / Pareja 6B",
            "scoreA": 4,
            "scoreB": 6,
            "court": "Pista 13",
            "time": "15:00",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 90,
            "teamA": "Angel Millan / Albert Estrella",
            "teamB": "Sergio Serrano / Amigo Sergio",
            "scoreA": 4,
            "scoreB": 1,
            "court": "Pista 11",
            "time": "15:30",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 91,
            "teamA": "Gerardo / Pablo Mena",
            "teamB": "Pareja 5A / Pareja 5B",
            "scoreA": 3,
            "scoreB": 2,
            "court": "Pista 12",
            "time": "15:30",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 92,
            "teamA": "Eloy / Ness",
            "teamB": "Pareja 6A / Pareja 6B",
            "scoreA": 3,
            "scoreB": 5,
            "court": "Pista 13",
            "time": "15:30",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 93,
            "teamA": "Angel Millan / Albert Estrella",
            "teamB": "Eloy / Ness",
            "scoreA": 5,
            "scoreB": 3,
            "court": "Pista 11",
            "time": "16:00",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 94,
            "teamA": "Gerardo / Pablo Mena",
            "teamB": "Pareja 6A / Pareja 6B",
            "scoreA": 5,
            "scoreB": 6,
            "court": "Pista 12",
            "time": "16:00",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 95,
            "teamA": "Sergio Serrano / Amigo Sergio",
            "teamB": "Pareja 5A / Pareja 5B",
            "scoreA": 3,
            "scoreB": 1,
            "court": "Pista 13",
            "time": "16:00",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 4095,
            "matchName": "Semi 1",
            "teamA": "Angel Millan / Albert Estrella",
            "teamB": "Gerardo / Pablo Mena",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "3ª Masculina",
            "time": "16:30",
            "court": "Pista ?"
        },
        {
            "id": 4096,
            "matchName": "Semi 2",
            "teamA": "Pareja 6A / Pareja 6B",
            "teamB": "Eloy / Ness",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "3ª Masculina",
            "time": "16:30",
            "court": "Pista ?"
        },
        {
            "id": 5097,
            "matchName": "Final",
            "teamA": "Ganador Semi 1",
            "teamB": "Ganador Semi 2",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "final",
            "category": "3ª Masculina",
            "time": "17:30",
            "court": "Pista 1"
        }
    ],
    "groups": [
        "A",
        "B",
        "C",
        "D"
    ],
    "categories": [
        "4ª Mixta",
        "4ª Masculina",
        "4ª Femenina",
        "3ª Mixta",
        "3ª Masculina"
    ],
    "playoffs": []
};
