const BAKED_DATA = {
    "matches": [
        {
            "id": 1,
            "teamA": "Juanma Leon / Raquel Fernandez",
            "teamB": "David Asensio / Anais Grebot",
            "scoreA": 2,
            "scoreB": 3,
            "court": "Pista 2",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 2,
            "teamA": "Paula Alves / Jose Luis Berga",
            "teamB": "Alex Cuadra / Pili Jorques",
            "scoreA": 2,
            "scoreB": 6,
            "court": "Pista 3",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 3,
            "teamA": "Juanma Leon / Raquel Fernandez",
            "teamB": "Paula Alves / Jose Luis Berga",
            "scoreA": 2,
            "scoreB": 1,
            "court": "Pista 2",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 4,
            "teamA": "David Asensio / Anais Grebot",
            "teamB": "Alex Cuadra / Pili Jorques",
            "scoreA": 1,
            "scoreB": 5,
            "court": "Pista 3",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 5,
            "teamA": "Juanma Leon / Raquel Fernandez",
            "teamB": "Alex Cuadra / Pili Jorques",
            "scoreA": 3,
            "scoreB": 1,
            "court": "Pista 2",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 6,
            "teamA": "David Asensio / Anais Grebot",
            "teamB": "Paula Alves / Jose Luis Berga",
            "scoreA": 3,
            "scoreB": 4,
            "court": "Pista 3",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 7,
            "teamA": "Toni Millan / Sonia Lopez",
            "teamB": "Kevin Mancilla / Lorena Arenas",
            "scoreA": 5,
            "scoreB": 1,
            "court": "Pista 5",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 8,
            "teamA": "Joaquim Salvat / Monica",
            "teamB": "Javier Frauca / Natalia Guash",
            "scoreA": 3,
            "scoreB": 6,
            "court": "Pista 6",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 9,
            "teamA": "Toni Millan / Sonia Lopez",
            "teamB": "Joaquim Salvat / Monica",
            "scoreA": 1,
            "scoreB": 4,
            "court": "Pista 5",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 10,
            "teamA": "Kevin Mancilla / Lorena Arenas",
            "teamB": "Javier Frauca / Natalia Guash",
            "scoreA": 6,
            "scoreB": 4,
            "court": "Pista 6",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 11,
            "teamA": "Toni Millan / Sonia Lopez",
            "teamB": "Javier Frauca / Natalia Guash",
            "scoreA": 3,
            "scoreB": 5,
            "court": "Pista 5",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 12,
            "teamA": "Kevin Mancilla / Lorena Arenas",
            "teamB": "Joaquim Salvat / Monica",
            "scoreA": 3,
            "scoreB": 6,
            "court": "Pista 6",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 13,
            "teamA": "Abel Francesc / Edith Alvarez",
            "teamB": "Carlota Calabuig / Jordi Seuba",
            "scoreA": 2,
            "scoreB": 6,
            "court": "Pista 7",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 14,
            "teamA": "Enrique Fontoba / Annabel Delgado",
            "teamB": "Cristina Vidal / Carlos Calasanz",
            "scoreA": 6,
            "scoreB": 5,
            "court": "Pista 8",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 15,
            "teamA": "Abel Francesc / Edith Alvarez",
            "teamB": "Enrique Fontoba / Annabel Delgado",
            "scoreA": 4,
            "scoreB": 3,
            "court": "Pista 7",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 16,
            "teamA": "Carlota Calabuig / Jordi Seuba",
            "teamB": "Cristina Vidal / Carlos Calasanz",
            "scoreA": 1,
            "scoreB": 2,
            "court": "Pista 8",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 17,
            "teamA": "Abel Francesc / Edith Alvarez",
            "teamB": "Cristina Vidal / Carlos Calasanz",
            "scoreA": 1,
            "scoreB": 2,
            "court": "Pista 7",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 18,
            "teamA": "Carlota Calabuig / Jordi Seuba",
            "teamB": "Enrique Fontoba / Annabel Delgado",
            "scoreA": 4,
            "scoreB": 1,
            "court": "Pista 8",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 19,
            "teamA": "Marta Murigaren / Jorge Rueda",
            "teamB": "Coral / Ismael Casares",
            "scoreA": 4,
            "scoreB": 2,
            "court": "Pista 9",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "D",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 20,
            "teamA": "Luis Pino / Raquel Perez",
            "teamB": "Fernando Garcia / Paz Lorezo",
            "scoreA": 4,
            "scoreB": 2,
            "court": "Pista 10",
            "time": "13:30",
            "category": "4ª Mixta",
            "group": "D",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 21,
            "teamA": "Marta Murigaren / Jorge Rueda",
            "teamB": "Luis Pino / Raquel Perez",
            "scoreA": 1,
            "scoreB": 5,
            "court": "Pista 9",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "D",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 22,
            "teamA": "Coral Nova / Ismael Casares",
            "teamB": "Fernando Garcia / Paz Lorezo",
            "scoreA": 4,
            "scoreB": 2,
            "court": "Pista 10",
            "time": "14:00",
            "category": "4ª Mixta",
            "group": "D",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 23,
            "teamA": "Marta Murigaren / Jorge Rueda",
            "teamB": "Fernando Garcia / Paz Lorezo",
            "scoreA": 6,
            "scoreB": 3,
            "court": "Pista 9",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "D",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 24,
            "teamA": "Coral Nova / Ismael Casares",
            "teamB": "Luis Pino / Raquel Perez",
            "scoreA": 5,
            "scoreB": 4,
            "court": "Pista 10",
            "time": "14:30",
            "category": "4ª Mixta",
            "group": "D",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 1024,
            "matchName": "Cuartos 1",
            "teamA": "Alex Cuadra / Pili Jorques",
            "teamB": "Marta Murigaren / Jorge Rueda",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Mixta",
            "time": "16:30",
            "court": "Pista 1"
        },
        {
            "id": 1025,
            "matchName": "Cuartos 2",
            "teamA": "Joaquim Salvat / Monica",
            "teamB": "Cristina Vidal / Carlos Calasanz",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Mixta",
            "time": "16:30",
            "court": "Pista 4"
        },
        {
            "id": 1026,
            "matchName": "Cuartos 3",
            "teamA": "Carlota Calabuig / Jordi Seuba",
            "teamB": "Javier Frauca / Natalia Guash",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Mixta",
            "time": "16:30",
            "court": "Pista 7"
        },
        {
            "id": 1027,
            "matchName": "Cuartos 4",
            "teamA": "Luis Pino / Raquel Perez",
            "teamB": "Juanma Leon / Raquel Fernandez",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Mixta",
            "time": "16:30",
            "court": "Pista 10"
        },
        {
            "id": 2028,
            "matchName": "Semi 1",
            "teamA": "Ganador Cuartos 1",
            "teamB": "Ganador Cuartos 2",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "4ª Mixta",
            "time": "17:00",
            "court": "Pista 1"
        },
        {
            "id": 2029,
            "matchName": "Semi 2",
            "teamA": "Ganador Cuartos 3",
            "teamB": "Ganador Cuartos 4",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "4ª Mixta",
            "time": "17:00",
            "court": "Pista 4"
        },
        {
            "id": 3030,
            "matchName": "Final",
            "teamA": "Ganador Semi 1",
            "teamB": "Ganador Semi 2",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "final",
            "category": "4ª Mixta",
            "time": "17:45",
            "court": "Pista 1"
        },
        {
            "id": 32,
            "teamA": "Sergio Albert / Joan Bernard",
            "teamB": "Oscar Cosco / Javier Hita",
            "scoreA": 4,
            "scoreB": 2,
            "court": "Pista 11",
            "time": "13:30",
            "category": "4ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 33,
            "teamA": "Vladimir Starciuc / Bernat Pecharoman",
            "teamB": "Juan Manuel Lopez / Fernando Rodriguez",
            "scoreA": 5,
            "scoreB": 2,
            "court": "Pista 12",
            "time": "13:30",
            "category": "4ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 34,
            "teamA": "Sergio Albert / Joan Bernard",
            "teamB": "Vladimir Starciuc / Bernat Pecharoman",
            "scoreA": 5,
            "scoreB": 3,
            "court": "Pista 11",
            "time": "14:00",
            "category": "4ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 35,
            "teamA": "Oscar Cosco / Javier Hita",
            "teamB": "Juan Manuel Lopez / Fernando Rodriguez",
            "scoreA": 4,
            "scoreB": 6,
            "court": "Pista 12",
            "time": "14:00",
            "category": "4ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 36,
            "teamA": "Sergio Albert / Joan Bernard",
            "teamB": "Juan Manuel Lopez / Fernando Rodriguez",
            "scoreA": 6,
            "scoreB": 3,
            "court": "Pista 11",
            "time": "14:30",
            "category": "4ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 37,
            "teamA": "Oscar Cosco / Javier Hita",
            "teamB": "Vladimir Starciuc / Bernat Pecharoman",
            "scoreA": 2,
            "scoreB": 3,
            "court": "Pista 12",
            "time": "14:30",
            "category": "4ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 38,
            "teamA": "Adria Boza / Marc Pijuan",
            "teamB": "Cristian Lasheras / Manu Sanhez",
            "scoreA": 2,
            "scoreB": 3,
            "court": "Pista 13",
            "time": "13:30",
            "category": "4ª Masculina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 39,
            "teamA": "Xavi Perea / Bryan Davila",
            "teamB": "Dani Astasio / Marc Valldosera",
            "scoreA": 1,
            "scoreB": 3,
            "court": "Pista 14",
            "time": "13:30",
            "category": "4ª Masculina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 40,
            "teamA": "Adria Boza / Marc Pijuan",
            "teamB": "Xavi Perea / Bryan Davila",
            "scoreA": 3,
            "scoreB": 5,
            "court": "Pista 13",
            "time": "14:00",
            "category": "4ª Masculina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 41,
            "teamA": "Cristian Lasheras / Manu Sanhez",
            "teamB": "Dani Astasio / Marc Valldosera",
            "scoreA": 4,
            "scoreB": 3,
            "court": "Pista 14",
            "time": "14:00",
            "category": "4ª Masculina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 42,
            "teamA": "Adria Boza / Marc Pijuan",
            "teamB": "Dani Astasio / Marc Valldosera",
            "scoreA": 4,
            "scoreB": 6,
            "court": "Pista 13",
            "time": "14:30",
            "category": "4ª Masculina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 43,
            "teamA": "Cristian Lasheras / Manu Sanhez",
            "teamB": "Xavi Perea / Bryan Davila",
            "scoreA": 5,
            "scoreB": 4,
            "court": "Pista 14",
            "time": "14:30",
            "category": "4ª Masculina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 4043,
            "matchName": "Semi 1",
            "teamA": "Sergio Albert / Joan Bernard",
            "teamB": "Dani Astasio / Marc Valldosera",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "4ª Masculina",
            "time": "16:30",
            "court": "Pista 2"
        },
        {
            "id": 4044,
            "matchName": "Semi 2",
            "teamA": "Cristian Lasheras / Manu Sanhez",
            "teamB": "Vladimir Starciuc / Bernat Pecharoman",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "4ª Masculina",
            "time": "16:30",
            "court": "Pista 5"
        },
        {
            "id": 5045,
            "matchName": "Final",
            "teamA": "Ganador Semi 1",
            "teamB": "Ganador Semi 2",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "final",
            "category": "4ª Masculina",
            "time": "17:15",
            "court": "Pista 2"
        },
        {
            "id": 47,
            "teamA": "Cristina Matamala / Olga Ferer",
            "teamB": "Judith Esquerre / Judit Pinad",
            "scoreA": 6,
            "scoreB": 4,
            "court": "Pista 1",
            "time": "13:30",
            "category": "4ª Femenina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 48,
            "teamA": "Anna Polo / Anna Gaseni",
            "teamB": "Noelia Omaque",
            "scoreA": 2,
            "scoreB": 6,
            "court": "Pista 4",
            "time": "13:30",
            "category": "4ª Femenina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 49,
            "teamA": "Cristina Matamala / Olga Ferer",
            "teamB": "Anna Polo / Anna Gaseni",
            "scoreA": 4,
            "scoreB": 3,
            "court": "Pista 1",
            "time": "14:00",
            "category": "4ª Femenina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 50,
            "teamA": "Judith Esquerre / Judit Pinad",
            "teamB": "Noelia Omaque",
            "scoreA": 1,
            "scoreB": 2,
            "court": "Pista 4",
            "time": "14:00",
            "category": "4ª Femenina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 51,
            "teamA": "Cristina Matamala / Olga Ferer",
            "teamB": "Noelia Omaque",
            "scoreA": 6,
            "scoreB": 5,
            "court": "Pista 1",
            "time": "14:30",
            "category": "4ª Femenina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 52,
            "teamA": "Judith Esquerre / Judit Pinad",
            "teamB": "Anna Polo / Anna Gaseni",
            "scoreA": 6,
            "scoreB": 2,
            "court": "Pista 4",
            "time": "14:30",
            "category": "4ª Femenina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 53,
            "teamA": "Sandra Riera / Yolanda Sanz",
            "teamB": "Gemma Saavedra / Mayte Vega",
            "scoreA": 1,
            "scoreB": 5,
            "court": "Pista 1",
            "time": "15:00",
            "category": "4ª Femenina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 54,
            "teamA": "Maria Lluisa Benlloch / Enma Baijet",
            "teamB": "Berta Cañas / Andrea Vivancos",
            "scoreA": 2,
            "scoreB": 1,
            "court": "Pista 4",
            "time": "15:00",
            "category": "4ª Femenina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 55,
            "teamA": "Sandra Riera / Yolanda Sanz",
            "teamB": "Maria Lluisa Benlloch / Enma Baijet",
            "scoreA": 6,
            "scoreB": 3,
            "court": "Pista 1",
            "time": "15:30",
            "category": "4ª Femenina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 56,
            "teamA": "Gemma Saavedra / Mayte Vega",
            "teamB": "Berta Cañas / Andrea Vivancos",
            "scoreA": 4,
            "scoreB": 2,
            "court": "Pista 4",
            "time": "15:30",
            "category": "4ª Femenina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 57,
            "teamA": "Sandra Riera / Yolanda Sanz",
            "teamB": "Berta Cañas / Andrea Vivancos",
            "scoreA": 5,
            "scoreB": 6,
            "court": "Pista 1",
            "time": "16:00",
            "category": "4ª Femenina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 58,
            "teamA": "Gemma Saavedra / Mayte Vega",
            "teamB": "Maria Lluisa Benlloch / Enma Baijet",
            "scoreA": 2,
            "scoreB": 4,
            "court": "Pista 4",
            "time": "16:00",
            "category": "4ª Femenina",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 59,
            "teamA": "Yoana Martinez / Andrea Baraja",
            "teamB": "Marta Bassons / Joana Garcia",
            "scoreA": 3,
            "scoreB": 2,
            "court": "Pista 7",
            "time": "15:00",
            "category": "4ª Femenina",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 60,
            "teamA": "Sheila Jodar / Greis Caballero",
            "teamB": "Marta Baijet / Mireia Peligros",
            "scoreA": 4,
            "scoreB": 6,
            "court": "Pista 10",
            "time": "15:00",
            "category": "4ª Femenina",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 61,
            "teamA": "Yoana Martinez / Andrea Baraja",
            "teamB": "Sheila Jodar / Greis Caballero",
            "scoreA": 3,
            "scoreB": 6,
            "court": "Pista 7",
            "time": "15:30",
            "category": "4ª Femenina",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 62,
            "teamA": "Marta Bassons / Joana Garcia",
            "teamB": "Marta Baijet / Mireia Peligros",
            "scoreA": 2,
            "scoreB": 6,
            "court": "Pista 10",
            "time": "15:30",
            "category": "4ª Femenina",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 63,
            "teamA": "Yoana Martinez / Andrea Baraja",
            "teamB": "Marta Baijet / Mireia Peligros",
            "scoreA": 5,
            "scoreB": 2,
            "court": "Pista 7",
            "time": "16:00",
            "category": "4ª Femenina",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 64,
            "teamA": "Marta Bassons / Joana Garcia",
            "teamB": "Sheila Jodar / Greis Caballero",
            "scoreA": 3,
            "scoreB": 5,
            "court": "Pista 10",
            "time": "16:00",
            "category": "4ª Femenina",
            "group": "C",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 1064,
            "matchName": "Cuartos 1",
            "teamA": "Cristina Matamala / Olga Ferer",
            "teamB": "3º Mejor (1)",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Femenina",
            "time": "16:30",
            "court": "Pista 3"
        },
        {
            "id": 1065,
            "matchName": "Cuartos 2",
            "teamA": "Maria Lluisa Benlloch / Enma Baijet",
            "teamB": "Marta Baijet / Mireia Peligros",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Femenina",
            "time": "16:30",
            "court": "Pista 6"
        },
        {
            "id": 1066,
            "matchName": "Cuartos 3",
            "teamA": "Gemma Saavedra / Mayte Vega",
            "teamB": "3º Mejor (2)",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Femenina",
            "time": "16:30",
            "court": "Pista 8"
        },
        {
            "id": 1067,
            "matchName": "Cuartos 4",
            "teamA": "Sheila Jodar / Greis Caballero",
            "teamB": "Noelia Omaque",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "quarter",
            "category": "4ª Femenina",
            "time": "16:30",
            "court": "Pista 9"
        },
        {
            "id": 2068,
            "matchName": "Semi 1",
            "teamA": "Ganador Cuartos 1",
            "teamB": "Ganador Cuartos 2",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "4ª Femenina",
            "time": "17:00",
            "court": "Pista 3"
        },
        {
            "id": 2069,
            "matchName": "Semi 2",
            "teamA": "Ganador Cuartos 3",
            "teamB": "Ganador Cuartos 4",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "4ª Femenina",
            "time": "17:00",
            "court": "Pista 6"
        },
        {
            "id": 3070,
            "matchName": "Final",
            "teamA": "Ganador Semi 1",
            "teamB": "Ganador Semi 2",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "final",
            "category": "4ª Femenina",
            "time": "17:45",
            "court": "Pista 3"
        },
        {
            "id": 72,
            "teamA": "Monica Muñoz / Miki Muñoz",
            "teamB": "David Navea / Ainhoa Navea",
            "scoreA": 2,
            "scoreB": 3,
            "court": "Pista 5",
            "time": "15:00",
            "category": "3ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 73,
            "teamA": "Manuel Gamero / Zizi",
            "teamB": "Falta Pareja / Falta Pareja 1",
            "scoreA": 4,
            "scoreB": 6,
            "court": "Pista 6",
            "time": "15:00",
            "category": "3ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 74,
            "teamA": "Monica Muñoz / Miki Muñoz",
            "teamB": "Manuel Gamero / Zizi",
            "scoreA": 2,
            "scoreB": 3,
            "court": "Pista 5",
            "time": "15:30",
            "category": "3ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 75,
            "teamA": "David Navea / Ainhoa Navea",
            "teamB": "Falta Pareja / Falta Pareja 1",
            "scoreA": 2,
            "scoreB": 1,
            "court": "Pista 6",
            "time": "15:30",
            "category": "3ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 76,
            "teamA": "Monica Muñoz / Miki Muñoz",
            "teamB": "Falta Pareja / Falta Pareja 1",
            "scoreA": 1,
            "scoreB": 5,
            "court": "Pista 5",
            "time": "16:00",
            "category": "3ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 77,
            "teamA": "David Navea / Ainhoa Navea",
            "teamB": "Manuel Gamero / Zizi",
            "scoreA": 1,
            "scoreB": 5,
            "court": "Pista 6",
            "time": "16:00",
            "category": "3ª Mixta",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 78,
            "teamA": "Ronny Benalcazar / Carla Soto",
            "teamB": "Juanjo / Mariona",
            "scoreA": 2,
            "scoreB": 3,
            "court": "Pista 8",
            "time": "15:00",
            "category": "3ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 79,
            "teamA": "Ramon Mejias / Lola Caro",
            "teamB": "Olga Phylbma / Mario Sanz",
            "scoreA": 1,
            "scoreB": 3,
            "court": "Pista 9",
            "time": "15:00",
            "category": "3ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 80,
            "teamA": "Ronny Benalcazar / Carla Soto",
            "teamB": "Ramon Mejias / Lola Caro",
            "scoreA": 1,
            "scoreB": 3,
            "court": "Pista 8",
            "time": "15:30",
            "category": "3ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 81,
            "teamA": "Juanjo / Mariona",
            "teamB": "Olga Phylbma / Mario Sanz",
            "scoreA": 5,
            "scoreB": 1,
            "court": "Pista 9",
            "time": "15:30",
            "category": "3ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 82,
            "teamA": "Ronny Benalcazar / Carla Soto",
            "teamB": "Olga Phylbma / Mario Sanz",
            "scoreA": 3,
            "scoreB": 1,
            "court": "Pista 8",
            "time": "16:00",
            "category": "3ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 83,
            "teamA": "Juanjo / Mariona",
            "teamB": "Ramon Mejias / Lola Caro",
            "scoreA": 3,
            "scoreB": 1,
            "court": "Pista 9",
            "time": "16:00",
            "category": "3ª Mixta",
            "group": "B",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 4083,
            "matchName": "Semi 1",
            "teamA": "Falta Pareja / Falta Pareja 1",
            "teamB": "Ronny / Carla",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "3ª Mixta",
            "time": "17:00",
            "court": "Pista 7"
        },
        {
            "id": 4084,
            "matchName": "Semi 2",
            "teamA": "Juanjo / Mariona",
            "teamB": "Manuel Gamero / Zizi",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "3ª Mixta",
            "time": "17:00",
            "court": "Pista 10"
        },
        {
            "id": 5085,
            "matchName": "Final",
            "teamA": "Ganador Semi 1",
            "teamB": "Ganador Semi 2",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "final",
            "category": "3ª Mixta",
            "time": "17:45",
            "court": "Pista 5"
        },
        {
            "id": 87,
            "teamA": "Angel Millan / Albert Estrella",
            "teamB": "Gerardo Jaenes / Pablo Mena",
            "scoreA": 4,
            "scoreB": 2,
            "court": "Pista 11",
            "time": "15:00",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 88,
            "teamA": "Sergio Serrano / Fernando Gomez",
            "teamB": "Eloy Arrabal / Ness Rodera",
            "scoreA": 2,
            "scoreB": 6,
            "court": "Pista 12",
            "time": "15:00",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 89,
            "teamA": "Toni Palau / Carlos Asmadt",
            "teamB": "Pablo Kellermann / Victor Iliana",
            "scoreA": 4,
            "scoreB": 6,
            "court": "Pista 13",
            "time": "15:00",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },

        {
            "id": 90,
            "teamA": "Angel Millan / Albert Estrella",
            "teamB": "Sergio Serrano / Fernando Gomez",
            "scoreA": 4,
            "scoreB": 1,
            "court": "Pista 11",
            "time": "15:30",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 91,
            "teamA": "Gerardo Jaenes / Pablo Mena",
            "teamB": "Toni Palau / Carlos Asmadt",
            "scoreA": 3,
            "scoreB": 2,
            "court": "Pista 12",
            "time": "15:30",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 92,
            "teamA": "Eloy Arrabal / Ness Rodera",
            "teamB": "Pablo Kellermann / Victor Iliana",
            "scoreA": 3,
            "scoreB": 5,
            "court": "Pista 13",
            "time": "15:30",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },

        {
            "id": 93,
            "teamA": "Angel Millan / Albert Estrella",
            "teamB": "Eloy Arrabal / Ness Rodera",
            "scoreA": 5,
            "scoreB": 3,
            "court": "Pista 11",
            "time": "16:00",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 94,
            "teamA": "Gerardo Jaenes / Pablo Mena",
            "teamB": "Pablo Kellermann / Victor Iliana",
            "scoreA": 5,
            "scoreB": 6,
            "court": "Pista 12",
            "time": "16:00",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },
        {
            "id": 95,
            "teamA": "Sergio Serrano / Fernando Gomez",
            "teamB": "Toni Palau / Carlos Asmadt",
            "scoreA": 3,
            "scoreB": 1,
            "court": "Pista 13",
            "time": "16:00",
            "category": "3ª Masculina",
            "group": "A",
            "status": "finished",
            "stage": "group"
        },

        {
            "id": 4095,
            "matchName": "Semi 1",
            "teamA": "Angel Millan / Albert Estrella",
            "teamB": "Gerardo Jaenes / Pablo Mena",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "3ª Masculina",
            "time": "17:00",
            "court": "Pista 8"
        },
        {
            "id": 4096,
            "matchName": "Semi 2",
            "teamA": "Pablo Kellermann / Victor Iliana",
            "teamB": "Eloy Arrabal / Ness Rodera",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "semi",
            "category": "3ª Masculina",
            "time": "17:00",
            "court": "Pista 9"
        },

        {
            "id": 5097,
            "matchName": "Final",
            "teamA": "Ganador Semi 1",
            "teamB": "Ganador Semi 2",
            "scoreA": null,
            "scoreB": null,
            "status": "pending",
            "stage": "final",
            "category": "3ª Masculina",
            "time": "17:45",
            "court": "Pista 6"
        }
    ],
    "groups": [
        "A",
        "B",
        "C",
        "D"
    ],
    "categories": [
        "4ª Mixta",
        "4ª Masculina",
        "4ª Femenina",
        "3ª Mixta",
        "3ª Masculina"
    ],
    "playoffs": []
};
